micronaut:
  application:
    name: nossaCasaDoCodigo
datasources:
  default:
    url: jdbc:mysql://localhost:3306/kotlinTeste?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    dialect: MySQL8Dialect
jpa.default.properties.hibernate.hbm2ddl.auto: update
